from __future__ import annotations

import abc
from pathlib import Path
from typing import TYPE_CHECKING, Iterable, List, Optional, Union

from .utility import Utility

if TYPE_CHECKING:
    from .alias import Alias
    from .environment import Environment

# Anything that can be passed to a builder as an input or dependency: a file path, a string
# (resolved relative to the source directory), an upstream Target, or a nested iterable of these.
InputLike = Union[str, Path, "Target", Iterable["InputLike"]]

# What a target produces: a real output file, a phony alias, or nothing (autogenerated/none).
OutputLike = Union[Path, "Alias", None]


class Target(abc.ABC):
    """A node in the build graph: one invocation of a builder.

    A target ties together the builder that produces it, its inputs and order-only
    dependencies, the output it generates, and the environment it was created in.
    Targets are produced by :meth:`nanobuild.environment.Environment.build` (i.e. by calling
    ``env.<BuilderName>(...)``) and can themselves be passed as inputs to other targets,
    which is how the dependency graph is wired together.

    :param builder_id: Name of the builder used to produce this target (e.g. ``'CXX'``).
    :param inputs: Input files and/or upstream :class:`Target` objects.
    :param output: Output path (:class:`~pathlib.Path`), an :class:`~nanobuild.alias.Alias`
        for phony targets, or ``None`` when the builder autogenerates the output.
    :param deps: Order-only dependencies (rebuilt before this target, but do not by
        themselves trigger a rebuild), e.g. header files.
    :param environment: The :class:`~nanobuild.environment.Environment` this target belongs to.
    :param command: For ``Command`` targets, the per-target shell command template (``{IN}``/``{OUT}``
        placeholders). ``None`` for targets that use their builder's shared rule.
    """

    def __init__(self,
                 builder_id: str,
                 inputs: InputLike,
                 output: OutputLike,
                 deps: InputLike,
                 environment: Environment,
                 command: Optional[str] = None) -> None:
        self.builder_id: str = builder_id
        self.output: OutputLike = output
        self.inputs: List[Union[str, Path, Target]] = Utility.flatten_list(inputs)
        self.deps: List[Union[str, Path, Target]] = Utility.flatten_list(deps)
        self.environment: Environment = environment
        self.command: Optional[str] = command
